import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[bell]
animation = "Linear"
color = "#424242"
command = "None"
duration = 5

[colors]
draw_bold_text_with_bright_colors = false
footer_bar = { foreground = "#181818", background = "#d8d8d8" }

[cursor]
blink_interval = 500
blink_timeout = 0
style = { shape = "Block", blinking = "Always" }
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"

[font]
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
builtin_box_drawing = true
glyph_offset = { x = 0, y = 0 }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
offset = { x = 0, y = 0 }
size = 24

[scrolling]
history = 10000
multiplier = 5

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
class = { general = "Alacritty", instance = "Alacritty" }
decorations = "none"
decorations_theme_variant = "None"
dimensions = { columns = 0, lines = 0 }
dynamic_padding = true
dynamic_title = false
opacity = 1.0
option_as_alt = "None"
padding = { x = 0, y = 0 }
position = { x = 0, y = 0 }
resize_increments = false
startup_mode = "Maximized"
title = "Alacritty"
