# --- options ---

layouts:
  - fullscreen
  #- tall
  #- wide
  #- column
  #- row

mod1:
  - option
  - shift

mod2:
  - option
  - shift
  - control

debug-layout-info: false
disable-padding-on-builtin-display: false
enables-layout-hud-on-space-change: false
enables-layout-hud: true
float-small-windows: true
floating:
  - com.apple.systempreferences
floating-is-blacklist: true
focus-follows-mouse: false
follow-space-thrown-windows: true
hide-menu-bar-icon: false
ignore-menu-bar: false
mouse-follows-focus: true
mouse-resizes-windows: true
mouse-swaps-windows: true
new-windows-to-main: false
restore-layouts-on-launch: true
screen-padding-bottom: 0
screen-padding-left: 0
screen-padding-right: 0
screen-padding-top: 0
smart-window-margins: true
use-canary-build: false
window-margin-size: 4
window-margins: true
window-max-count: 0
window-minimum-height: 0
window-minimum-height: 0
window-minimum-width: 0
window-minimum-width: 0
window-resize-step: 5

# --- bindings ---

# mod1+space
cycle-layout:
  mod: <NONE>
  key: <NONE>

# mod2+space
cycle-layout-backward:
  mod: <NONE>
  key: <NONE>

# mod1+h
shrink-main:
  mod: <NONE>
  key: <NONE>

# mod1+l
expand-main:
  mod: <NONE>
  key: <NONE>

# mod1+,
increase-main:
  mod: <NONE>
  key: <NONE>

# mod1+.
decrease-main:
  mod: <NONE>
  key: <NONE>

# mod1+j
focus-ccw:
  mod: <NONE>
  key: <NONE>

# mod1+k
focus-cw:
  mod: <NONE>
  key: <NONE>

# mod1+m
focus-main:
  mod: <NONE>
  key: <NONE>

# mod1+p
focus-screen-ccw:
  mod: <NONE>
  key: <NONE>

# mod1+n
focus-screen-cw:
  mod: <NONE>
  key: <NONE>

# mod2+h
swap-screen-ccw:
  mod: <NONE>
  key: <NONE>

# mod2+l
swap-screen-cw:
  mod: <NONE>
  key: <NONE>

# mod2+j
swap-ccw:
  mod: <NONE>
  key: <NONE>

# mod2+k
swap-cw:
  mod: <NONE>
  key: <NONE>

# mod1+enter
swap-main:
  mod: <NONE>
  key: <NONE>

focus-screen-1:
  mod: mod1
  key: '['
throw-screen-1:
  mod: mod2
  key: '['
focus-screen-2:
  mod: mod1
  key: ']'
throw-screen-2:
  mod: mod2
  key: ']'

throw-space-1:
  mod: mod2
  key: '1'
throw-space-2:
  mod: mod2
  key: '2'
throw-space-3:
  mod: mod2
  key: '3'
throw-space-4:
  mod: mod2
  key: '4'
throw-space-5:
  mod: mod2
  key: '5'
throw-space-6:
  mod: mod2
  key: '6'
throw-space-7:
  mod: mod2
  key: '7'
throw-space-8:
  mod: mod2
  key: '8'

select-fullscreen-layout:
  mod: <NONE>
  key: <NONE>

select-tall-layout:
  mod: <NONE>
  key: <NONE>

select-wide-layout:
  mod: <NONE>
  key: <NONE>

select-column-layout:
  mod: <NONE>
  key: <NONE>

select-row-layout:
  mod: <NONE>
  key: <NONE>

throw-space-left:
  mod: <NONE>
  key: <NONE>

throw-space-right:
  mod: <NONE>
  key: <NONE>

# mod1+t
toggle-float:
  mod: <NONE>
  key: <NONE>

# mod1+i
display-current-layout:
  mod: <NONE>
  key: <NONE>

# mod2+t
toggle-tiling:
  mod: <NONE>
  key: <NONE>

# mod1+z
reevaluate-windows:
  mod: mod1
  key: '\'

toggle-focus-follows-mouse:
  mod: <NONE>
  key: <NONE>

# mod2+z
relaunch-amethyst:
  mod: <NONE>
  key: <NONE>

